### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by hardikpthv** [online-edu/react-weather#2]
**Task**

- [x] Use the OpenWeatherMap 5 day weather forecast API to retrieve and display the current 5-day weather forecast for a city (ex. Vancouver): http://openweathermap.org/forecast5

**Stretch Goals**

- [x] Create a responsive version
- [x] Add a feature to explore the weather information in other cities
- [x] Deploy your assignment somewhere and include the link in your README so we can try it out
